package com.punit.angular.domain;
// Generated Oct 27, 2018 2:05:41 PM by Hibernate Tools 4.3.1



/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private Integer stockId;
     private String stockCode;
     private String stockName;

    public Stock() {
    }

    public Stock(String stockCode, String stockName) {
       this.stockCode = stockCode;
       this.stockName = stockName;
    }
   
    public Integer getStockId() {
        return this.stockId;
    }
    
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }
    public String getStockCode() {
        return this.stockCode;
    }
    
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode;
    }
    public String getStockName() {
        return this.stockName;
    }
    
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }




}


